# Generated by Django 4.1.4 on 2022-12-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_projectfiles_image_alter_projectfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
